### ISSUE TITLE
API Endpoint Incorrect Structure

### ISSUE THREAD

**Issue by vvaths** [mona-actions/gh-migrate-releases#6]
### Describe the bug

The base URL seems to be wrong. It's using https://github.com/api/v3 instead of https://api.github.com.

### To Reproduce

run ```gh migrate-releases export --hostname github.com -o <org> --repository <repo> --token <pat>```
or ```sync``` command

see this output:
```
  FATAL   Error getting releases: unable to get releases: GET https://github.com/api/v3/repos/<org>/<repo>/releases?per_page=100: 404  []panic:

goroutine 1 [running]:
github.com/pterm/pterm.checkFatal(...)
        github.com/pterm/pterm@v0.12.79/prefix_printer.go:351
github.com/pterm/pterm.(*PrefixPrinter).Printf(0x1149b80, {0xd4ae5c, 0x1a}, {0xc000119b80, 0x1, 0x1})
        github.com/pterm/pterm@v0.12.79/prefix_printer.go:278 +0x1a5
github.com/mona-actions/gh-migrate-releases/pkg/export.CreateJSONs()
        github.com/mona-actions/gh-migrate-releases/pkg/export/export.go:19 +0x14c
github.com/mona-actions/gh-migrate-releases/cmd.glob..func1(0xc00011c200?, {0xd3d985?, 0x4?, 0xd3d989?})
        github.com/mona-actions/gh-migrate-releases/cmd/export.go:47 +0x36f
github.com/spf13/cobra.(*Command).execute(0x114b9c0, {0xc00011b000, 0x8, 0x8})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x114bca0)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mona-actions/gh-migrate-releases/cmd.Execute()
        github.com/mona-actions/gh-migrate-releases/cmd/root.go:26 +0x1a
main.main()
        github.com/mona-actions/gh-migrate-releases/main.go:9 +0xf
```
### Expected behavior

api.github.com base url structure and no errors

### Environment

using gh cli with git bash on windows

**Comment by amenocal** [comment]
hi @vvaths when talking to `github.com` you don't need to specify the hostname. you would onyl need to run it like this:

```
gh migrate-releases export -o <org> --repository <repo> --token <pat
```

the flag `--hostname` is only used when talking to a GitHub Enterprise Server hostname like `github.company.com`. Hope this helps.
